import { createHmac } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ upsert: vi.fn(), update: vi.fn(), events: vi.fn(), due: vi.fn(), deliveryUpdate: vi.fn(), mail: vi.fn(), transport: vi.fn(), lookup: vi.fn() }));
vi.mock("nodemailer",()=>({default:{createTransport:mocks.transport}}));
vi.mock("node:dns/promises",()=>({lookup:mocks.lookup}));
vi.mock("../db.js",()=>{
  const tx = { ownerNotificationSettings: { upsert: mocks.upsert,update:mocks.update }, $queryRaw:vi.fn(), paymentEvent:{findMany:mocks.events},billCollectorState:{findMany:async()=>[]},ownerNotificationDelivery:{findMany:mocks.due,updateMany:mocks.deliveryUpdate},ownerNotificationSeen:{findUnique:async()=>null,create:async()=>({})} };
  return {db:{...tx,$transaction:async(cb:(tx:any)=>Promise<unknown>)=>cb(tx)}};
});
import { feishuSignature, maskedOwnerSettings, mergeOwnerSettings, publicSmtpAddress, runOwnerNotifications, saveOwnerSettings, selectedOwnerEvent, sendOwnerNotification, validateFeishuWebhook, type OwnerSettings } from "../services/owner-notification-service.js";
import { openSealed,seal } from "../lib/crypto.js";
import { resetConfigForTests } from "../config.js";
const initial:OwnerSettings={emailEnabled:true,feishuEnabled:true,smtpHost:"smtp.example.com",smtpPort:465,smtpUser:"user",from:"from@example.com",to:"to@example.com",smtpPassword:"dummy-password",feishuWebhook:"https://open.feishu.cn/open-apis/bot/v2/hook/11111111-1111-1111-1111-111111111111",feishuSecret:"dummy-secret",paymentSuccess:true,anomalies:true,webhookFailure:true,collectorFailure:true};
let row:{payloadEncrypted:string;revision:number;createdAt:Date};
beforeEach(()=>{vi.clearAllMocks();resetConfigForTests();row={payloadEncrypted:seal(JSON.stringify(initial)),revision:1,createdAt:new Date()};mocks.upsert.mockImplementation(async()=>row);mocks.update.mockImplementation(async({data})=>{row={...row,payloadEncrypted:data.payloadEncrypted,revision:row.revision+1};return row;});mocks.events.mockResolvedValue([]);mocks.due.mockResolvedValue([]);mocks.deliveryUpdate.mockResolvedValue({count:1});mocks.transport.mockReturnValue({sendMail:mocks.mail,close:vi.fn()});mocks.mail.mockResolvedValue({});mocks.lookup.mockResolvedValue([{address:"8.8.8.8"}]);});
afterEach(()=>vi.unstubAllGlobals());
function input(extra:Record<string,unknown>={}){const {smtpPassword:_p,feishuWebhook:_w,feishuSecret:_s,...values}=initial;return {...values,revision:1,...extra};}
describe("owner notification security and delivery",()=>{
  it("rejects enabled placeholder secrets",()=>{expect(()=>mergeOwnerSettings(initial,input({smtpPassword:"replace-with-password"}))).toThrow();expect(()=>mergeOwnerSettings(initial,input({feishuSecret:"replace-with-secret"}))).toThrow();});
  it("cancels queued tasks when the channel is disabled",async()=>{row.payloadEncrypted=seal(JSON.stringify({...initial,emailEnabled:false}));mocks.due.mockResolvedValue([{id:"mail",channel:"EMAIL",title:"title",message:"body",attempts:0}]);await runOwnerNotifications();expect(mocks.mail).not.toHaveBeenCalled();expect(mocks.deliveryUpdate).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:"mail"}),data:expect.objectContaining({status:"CANCELLED"})}));});
  it("marks a task dead after the fifth failed attempt without leaking SDK errors",async()=>{mocks.due.mockResolvedValue([{id:"mail",channel:"EMAIL",title:"title",message:"body",attempts:4}]);mocks.mail.mockRejectedValue(new Error("dummy-password"));await runOwnerNotifications();expect(mocks.deliveryUpdate).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:"mail"}),data:expect.objectContaining({status:"DEAD",lastError:"SEND_FAILED_CHECK_CHANNEL_CONFIG"})}));});
  it("masks all secrets including webhook URL",()=>{const result=maskedOwnerSettings(initial,1);expect(result).not.toHaveProperty("smtpPassword");expect(result).not.toHaveProperty("feishuWebhook");expect(result).not.toHaveProperty("feishuSecret");expect(result.feishuWebhookConfigured).toBe(true);});
  it("retains blank secrets and encrypts saved configuration",async()=>{await saveOwnerSettings(input({smtpPassword:"",feishuWebhook:"",feishuSecret:""}));expect(JSON.parse(openSealed(row.payloadEncrypted))).toEqual(initial);expect(row.payloadEncrypted).not.toContain(initial.smtpPassword);});
  it("supports explicit clearing only after disabling affected channels",()=>{const result=mergeOwnerSettings(initial,input({emailEnabled:false,feishuEnabled:false,smtpPassword:null,feishuWebhook:null,feishuSecret:null}));expect(result.smtpPassword).toBe("");expect(result.feishuWebhook).toBe("");expect(()=>mergeOwnerSettings(initial,input({smtpPassword:null}))).toThrow();});
  it("rejects stale settings revisions",async()=>{await expect(saveOwnerSettings(input({revision:2}))).rejects.toMatchObject({code:"SETTINGS_CONFLICT"});});
  it("rejects arbitrary webhook hosts, credentials, query strings and paths",()=>{for(const value of ["http://open.feishu.cn/open-apis/bot/v2/hook/11111111111111111111","https://evil.example/hook/11111111111111111111",initial.feishuWebhook+"?redirect=1","https://user@open.feishu.cn/open-apis/bot/v2/hook/11111111111111111111"])expect(()=>validateFeishuWebhook(value)).toThrow();});
  it("blocks private and mapped IPv6 SMTP destinations",()=>{for(const value of ["127.0.0.1","10.0.0.1","::1","::ffff:7f00:1","::ffff:a00:1","fe90::1","fd00::1"])expect(publicSmtpAddress(value)).toBe(false);expect(publicSmtpAddress("8.8.8.8")).toBe(true);});
  it("signs feishu requests with timestamp/secret HMAC and checks business ack",async()=>{expect(feishuSignature("123","secret")).toBe(createHmac("sha256","123\nsecret").update("").digest("base64"));const fetch=vi.fn(async(_url:unknown,_init:RequestInit)=>new Response('{"code":0}'));vi.stubGlobal("fetch",fetch);await sendOwnerNotification("FEISHU","title","body",initial);expect(JSON.parse(fetch.mock.calls[0]![1]!.body as string)).toMatchObject({msg_type:"text",sign:expect.any(String)});});
  it("rejects provider failures despite HTTP 200",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response('{"code":19021}')));await expect(sendOwnerNotification("FEISHU","title","body",initial)).rejects.toThrow();});
  it("requires verified TLS and pins resolved SMTP address",async()=>{await sendOwnerNotification("EMAIL","title","body",initial);expect(mocks.transport).toHaveBeenCalledWith(expect.objectContaining({host:"8.8.8.8",requireTLS:true,tls:{servername:initial.smtpHost,rejectUnauthorized:true}}));expect(mocks.mail).toHaveBeenCalledWith(expect.objectContaining({to:initial.to,text:"body"}));});
  it("retries email failures without blocking feishu delivery",async()=>{mocks.due.mockResolvedValue([{id:"mail",channel:"EMAIL",title:"title",message:"body",attempts:0},{id:"feishu",channel:"FEISHU",title:"title",message:"body",attempts:0}]);mocks.mail.mockRejectedValue(new Error("sensitive password must not leak"));vi.stubGlobal("fetch",vi.fn(async()=>new Response('{"code":0}')));await runOwnerNotifications();expect(mocks.deliveryUpdate).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:"mail"}),data:expect.objectContaining({status:"PENDING",lastError:"SEND_FAILED_CHECK_CHANNEL_CONFIG"})}));expect(mocks.deliveryUpdate).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({id:"feishu"}),data:expect.objectContaining({status:"SUCCESS"})}));});
  it("honors event switches",()=>{expect(selectedOwnerEvent("ORDER_SUCCEEDED",{...initial,paymentSuccess:false})).toBe(false);expect(selectedOwnerEvent("BUSINESS_WEBHOOK_DEAD",{...initial,webhookFailure:false})).toBe(false);});
});
